#!/usr/bin/env bash
set -e

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--prefix)
      PREFIX="$2"
      shift # past argument
      shift # past value
      ;;
    -d|--dry-run)
      DRY_RUN=YES
      shift # past argument
      ;;
    --default)
      DEFAULT=YES
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

if [ "$PREFIX" = "" ]; then
  echo please specify branch name prefix
  exit 1
fi

target_list=( $(git branch -r --list "origin/$PREFIX*") )

if [ "${#target_list[@]}" -eq "0" ]; then
    echo "branches the name of which name starts with \"$PREFIX\" are not found"
    exit 1
fi

# show target branches
for t in "${target_list[@]}"
do
  echo "  delete branch: $t"
done

if [ "$DRY_RUN" = "YES" ]; then
  echo finished dry run
  exit 0
fi

read -n1 -p "delete these branches from remote ? (Y/n): " yn
echo
if [[ ! $yn = [Y] ]]; then
  echo deleting branches canceled
  exit 1
fi

for t in "${target_list[@]}"
do
  branch_name=$(echo $t | cut -c 8-)
  git push origin --delete $branch_name
done

