#!/usr/bin/env bash
set -e

echo "Hello gh-delete-remote-branch!"

POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--prefix)
      PREFIX="$2"
      shift # past argument
      shift # past value
      ;;
    -d|--dry-run)
      DRY_RUN=YES
      shift # past argument
      ;;
    --default)
      DEFAULT=YES
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

target_list=( $(git branch -r --list "origin/$PREFIX*") )

if [ "$DRY_RUN" = "YES" ]; then
  echo dry run
  for t in "${target_list[@]}"
  do
    echo "delete branch: $t"
  done
  exit 0
fi

for t in "${target_list[@]}"
do
  branch_name=$(echo $t | cut -c 8-)
  echo git push origin --delete $branch_name
done

